global-variables:
  environment: &default_environment
    REGISTRY:
      from_secret: artifactory-host-01
    REGISTRY_HELM_PROJECT:  
      from_secret: artifactory-helm-project-01    
    USERNAME:
      from_secret: artifactory-user-01
    PASSWORD:
      from_secret: artifactory-password-01

kind: pipeline
type: docker
name: id-generator-with-drone
platform:
  os: linux
  arch: amd64 

steps:

  # - name: Fix permissions on build-output directory
  #   image: alpine
  #   volumes:  
  #   - name: build-output
  #     path: /drone/src/dist
  #   commands:
  #   - chown -R 1001:0 /drone/cache && chmod -R g+=wrx /drone/src/dist

  - name: Build dist
    image: node:16
    volumes:
    # - name: build-output
    #   path: /drone/src/dist
    commands:
    - npm install -g npm@latest
    - npm run build

  - name: Prepare registry secrets
    image: alpine
    volumes:  
    - name: dockerconfig
      path: /dockerconfig
    environment:
      DOCKER_CONFIG:
        from_secret: artifactory-dockerconfig-01
    commands:
    - echo "$DOCKER_CONFIG" > /dockerconfig/config.json
  
  - name: Build image
    image: gcr.io/kaniko-project/executor:debug
    environment:
      <<: *default_environment
    volumes:
    # - name: build-output
    #   path: /app-build
    - name: dockerconfig
      path: /kaniko/.docker
    commands:
    - >
      /kaniko/executor 
      --context /drone/src/dist
      --dockerfile Dockerfile
      --destination $${REGISTRY}/itsm/id-generator:test
      --no-push  
    when:
      event:
        exclude:
        - tag

## only on release
  - name: Build and push image
    image: gcr.io/kaniko-project/executor:debug
    environment:
      <<: *default_environment
    volumes:
    - name: dockerconfig
      path: /kaniko/.docker
    commands:
    - >
      /kaniko/executor 
      --context /drone/src/dist
      --dockerfile Dockerfile
      --destination $${REGISTRY}/itsm/id-generator:latest
      --destination $${REGISTRY}/itsm/id-generator:${DRONE_TAG}
    when:
      event:
      - tag
      ref:
      - refs/tags/v* 

volumes:
- name: build-output
  temp: {}
- name: dockerconfig
  temp: {}

trigger:
  event:
  - tag
  - push
  - pull_request